language: java


services:
  - mysql

build:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:

  - mvn clean verify

before_install:
  - chmod +x mvnw
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)
  - mysql -e 'CREATE DATABASE viandasya;'
  - mysql -e 'USE viandasya;'


test:
  - mvn test -B

after_success:
  - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r target/site/jacoco/jacoco.xml

